### ISSUE TITLE
It does not stop `UseRabbitMQ` when I `UseInMemoryMessageQueue` in `WebApplicationFactory` for testing.

### ISSUE THREAD

**Issue by chinaq** [yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue#2]
It does not stop `UseRabbitMQ` when I `UseInMemoryMessageQueue` in `WebApplicationFactory` for testing.

According to the [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#) Document, I have tried to set `UseInMemoryMessageQueue` in `Customized WebApplicationFactory`, but it did not work. When it started, it would connect to rabbitmq as before. How can I set it in `Customized WebApplicationFactory`?

``` cs
// customized web application factory

    public class MemoryWebApplicationFactory<TStartup> :
            WebApplicationFactory<TStartup> 
            where TStartup : class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                // Create a new service provider.
                var serviceProvider = new ServiceCollection()
                    .AddEntityFrameworkInMemoryDatabase()
                    .BuildServiceProvider();

                ......

                services.AddTransient<NBMeterDataArrivedIntegrationEventHandler>();
                services.AddCap(x => 
                {
                    x.UseInMemoryStorage();
                    x.UseInMemoryMessageQueue();
                });
               ......
            });
        }
    }
}
```

``` cs
// startup.cs
......
            services.AddTransient<NBMeterDataArrivedIntegrationEventHandler>();

            services.AddCap(x => 
            {
                x.UseInMemoryStorage();
                x.UseRabbitMQ(conf =>
                {
                    conf.HostName = Configuration["EventBusConnection"];
                    conf.UserName = Configuration["EventBusUserName"];
                    conf.Password = Configuration["EventBusPassword"];
                });
                x.UseDashboard();
            });
......
```

``` cs
// test file
   public class MeterDataTest:
        IClassFixture<MemoryWebApplicationFactory<Startup>>
    {
        private readonly ITestOutputHelper _output;
        private readonly HttpClient _client;
        private readonly MemoryWebApplicationFactory<Startup> _factory;

        public MeterDataTest(ITestOutputHelper output, MemoryWebApplicationFactory<Startup> factory)
        {
            _output = output;
            _factory = factory;
            _client = factory.CreateClient();
        }

        [Fact]
        public async Task MeterDataArrivedIntegrationEvent()
        {
        //When
            var response = await _client.GetAsync("api/MeterData");
        //Then
            response.EnsureSuccessStatusCode();
            ...
        }
```

``` bash
# error message

DotNetCore.CAP.BrokerConnectionException: Broker Unreachable ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.AggregateException: One or more errors occurred. (Connection failed) ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 127.0.0.1:5672
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__272_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at RabbitMQ.Client.TcpClientAdapter.ConnectAsync(String host, Int32 port)
   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, Int32 millisecondsTimeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 timeout, AddressFamily family)
   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 connectionTimeout, Int32 readTimeout, Int32 writeTimeout)
   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.GetConnection() in C:\projects\cap\src\DotNetCore.CAP.RabbitMQ\IConnectionChannelPool.Default.cs:line 77
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.InitClient() in C:\projects\cap\src\DotNetCore.CAP.RabbitMQ\RabbitMQConsumerClient.cs:line 93
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId) in C:\projects\cap\src\DotNetCore.CAP.RabbitMQ\RabbitMQConsumerClientFactory.cs:line 21
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId) in C:\projects\cap\src\DotNetCore.CAP.RabbitMQ\RabbitMQConsumerClientFactory.cs:line 25
   at DotNetCore.CAP.ConsumerRegister.<>c__DisplayClass14_0.<Start>b__0() in C:\projects\cap\src\DotNetCore.CAP\IConsumerRegister.Default.cs:line 67
```

**Comment by yang-xiaodong** [comment]
You can't configuration `UseRabbitMQ` and `UseInMemoryMessageQueue` at the same time

**Comment by chinaq** [comment]
@yang-xiaodong But when I set it all in `Startup.cs`, that works and does not connect to RabbitMQ. Codes like

``` cs
// Startup.cs

            services.AddCap(x => 
            {
                x.UseInMemoryStorage();
                x.UseRabbitMQ(conf =>
                {
                    conf.HostName = Configuration["EventBusConnection"];
                    conf.UserName = Configuration["EventBusUserName"];
                    conf.Password = Configuration["EventBusPassword"];
                });
                x.UseDashboard();
            });

            services.AddCap(x => 
            {
                x.UseInMemoryStorage();
                x.UseInMemoryMessageQueue();
            });
......
```

**Comment by yang-xiaodong** [comment]
Why did you configure  `services.AddCap` twice ?

**Comment by chinaq** [comment]
It does not for real application.
- At first, I just wanted to redo the `AddCap` by `In Memory Queue` in `MemoryWebApplicationFactory.cs` for integration test.
- But it failed, it would connect the `rabbit mq` as before.
- At that time, I supposed that it was impossible to configure `services.AddCap` twice.
- But when I tried to set it all in `Startup.cs`, it worked by `In Memory Queue`.
- It confused me that setting `AddCap` twice works in `Startup.cs` and does not work in `MemoryWebApplicationFactory.cs`

Finally I have set a mock `Startup.cs`, in which I redo the `AddCap` by `In Memory Queue`,  for integration test only.

**Comment by yang-xiaodong** [comment]
你用汉字吧，你这个英文我看不懂啊，你用的翻译器翻译的吧？

`But when I tried to set it all in Startup.cs` , it worked by In Memory Queue
但是当我试图在 Startup.cs 设置所有, In Memory Queue 这时工作了
但是当我试图在 Startup.cs 设置  In Memory Queue 它工作了

都不通顺啊， all 是指的什么？it 值的是什么？设置两次?

**Comment by chinaq** [comment]
是这样的
``` cs
// Startup.cs

            services.AddCap(x => 
            {
                x.UseInMemoryStorage();
                x.UseRabbitMQ(conf =>
                {
                    conf.HostName = Configuration["EventBusConnection"];
                    conf.UserName = Configuration["EventBusUserName"];
                    conf.Password = Configuration["EventBusPassword"];
                });
                x.UseDashboard();
            });

            services.AddCap(x => 
            {
                x.UseInMemoryStorage();
                x.UseInMemoryMessageQueue();
            });
......
```

如果仅在这个 `Startup.cs` 文件中这样设置，后者是有效的，CAP 会只使用内存队列。

但是，用[顶楼的方法设置](https://github.com/yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue/issues/2#issue-472191738)，即`Startup.cs`和`MemoryWebApplicationFactory.cs`中各设置一次，后者是无效的，CAP 只会使用 Rabbit MQ 的队列。

**Comment by yang-xiaodong** [comment]
你在跑集成测试前向系统写入一个环境变量，然后这里根据环境变量来加载不同的配置不就行了？ 为啥要这样？

**Comment by chinaq** [comment]
其实完全可以按你说的这样运行。只是在写程序时，发现以上两种情况，得到的结果不一样，所以就提问了。

**Comment by yang-xiaodong** [comment]
不支持你这样配置
